AWSTemplateFormatVersion: 2010-09-09
Outputs:
  LokiDynamoDBServiceAccountPolicy:
    Export:
      Name:
        Fn::Sub: ${AWS::StackName}-LokiDynamoDBServiceAccountPolicy
    Value:
      Ref: LokiDynamoDBServiceAccountPolicy
Resources:
  LokiDynamoDBServiceAccountPolicy:
    Properties:
      Description: Service account policy for storing indexes in an DynamoDB table
      ManagedPolicyName: okctl-julius-LokiDynamoDBServiceAccountPolicy
      PolicyDocument:
        Statement:
        - Action:
          - dynamodb:BatchGetItem
          - dynamodb:BatchWriteItem
          - dynamodb:UntagResource
          - dynamodb:PutItem
          - dynamodb:DeleteItem
          - dynamodb:ListTagsOfResource
          - dynamodb:Query
          - dynamodb:UpdateItem
          - dynamodb:DeleteTable
          - dynamodb:CreateTable
          - dynamodb:TagResource
          - dynamodb:DescribeTable
          - dynamodb:GetItem
          - dynamodb:UpdateTable
          Effect: Allow
          Resource:
          - arn:aws:dynamodb:eu-west-1::table/okctl-julius-loki-index_*
        - Action:
          - dynamodb:ListTables
          Effect: Allow
          Resource:
          - arn:aws:dynamodb:eu-west-1::table/*
        Version: 2012-10-17
    Type: AWS::IAM::ManagedPolicy
