apiVersion: v1
kind: Pod
metadata:
  name: debugger
spec:
  containers:
  - image: markeijsermans/debug:kitchen-sink
    name: debugger
    command: ["/bin/sh", "-c", "sleep 3600"]
    volumeMounts:
    - mountPath: /prometheus
      name: prometheus-data
  volumes:
  - name: prometheus-data
    persistentVolumeClaim:
      claimName: prometheus-data-embedded-prometheus-kube-prometheus-stack-prometheus-0
