apiVersion: kubernetes-client.io/v1
kind: ExternalSecret

metadata:
  name: grafana-secrets-cm
  namespace: monitoring

spec:
  backendType: systemManager
  data:
  - key: /okctl/${CLUSTER_NAME}/client-secret
    name: client-secret
  - key: /okctl/${CLUSTER_NAME}/secret-key
    name: secret-key
  - key: /okctl/${CLUSTER_NAME}/admin-user
    name: admin-user
  - key: /okctl/${CLUSTER_NAME}/admin-pass
    name: admin-pass
