apiVersion: kubernetes-client.io/v1
kind: ExternalSecret

metadata:
  name: argocd-privatekey
  namespace: argocd

spec:
  backendType: systemManager
  data:
  - key: /okctl/${CLUSTER_NAME}/github/deploykeys/oslokommune/${REPOSITORY_NAME}/privatekey
    name: sshPrivateKey
  template:
    metadata:
      labels:
        argocd.argoproj.io/secret-type: repository
    stringData:
      name: oslokommune/${REPOSITORY_NAME}
      type: git
      url: git@github.com:oslokommune/${REPOSITORY_NAME}
