apiVersion: kubernetes-client.io/v1
kind: ExternalSecret

metadata:
  name: argocd-secret
  namespace: argocd

spec:
  backendType: systemManager
  data:
  - key: /okctl/${CLUSTER_NAME}/argocd/client-secret
    name: dex.cognito.clientSecret
  - key: /okctl/${CLUSTER_NAME}/argocd/secret-key
    name: server.secretkey
