AWSTemplateFormatVersion: 2010-09-09
Outputs:
  PublicCertificate:
    Export:
      Name:
        Fn::Sub: ${AWS::StackName}-PublicCertificate
    Value:
      Ref: PublicCertificate
Resources:
  PublicCertificate:
    Properties:
      DomainName: argocd.${CLUSTER_NAME}.oslo.systems
      DomainValidationOptions:
      - DomainName: argocd.${CLUSTER_NAME}.oslo.systems
        HostedZoneId: ${HOSTED_ZONE_ID}
      ValidationMethod: DNS
    Type: AWS::CertificateManager::Certificate
