AWSTemplateFormatVersion: 2010-09-09
Outputs:
  argocdClientID:
    Export:
      Name:
        Fn::Sub: ${AWS::StackName}-argocdClientID
    Value:
      Ref: UserPoolClientargocd
Resources:
  UserPoolClientargocd:
    Properties:
      AllowedOAuthFlows:
      - code
      AllowedOAuthFlowsUserPoolClient: true
      AllowedOAuthScopes:
      - email
      - profile
      - openid
      CallbackURLs:
      - https://argocd.${CLUSTER_NAME}.oslo.systems/api/dex/callback
      ClientName: okctl-${CLUSTER_NAME}-argocd
      DefaultRedirectURI: https://argocd.${CLUSTER_NAME}.oslo.systems/api/dex/callback
      GenerateSecret: true
      PreventUserExistenceErrors: ENABLED
      RefreshTokenValidity: 30
      SupportedIdentityProviders:
      - COGNITO
      UserPoolId: ${USER_POOL_ID}
    Type: AWS::Cognito::UserPoolClient
