apiVersion: v1
kind: ConfigMap

metadata:
  name: loki-datasource
  namespace: monitoring
  labels:
    grafana_datasource: "1"

data:
  loki-datasource.yaml: |
    apiVersion: 1
    datasources:
    - access: proxy
      basicAuth: false
      editable: false
      jsonData:
        tlsSkipVerify: true
      name: Loki
      orgId: 1
      type: loki
      url: http://loki:3100
      version: 1
