apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Name }}
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: {{ .TargetDir }}
    repoURL: {{ .RepositoryURI }}
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: false

---
