apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: autoscaler
  namespace: argocd
  labels:
    provider: okctl
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
  source:
    chart: cluster-autoscaler
    repoURL: "https://kubernetes.github.io/autoscaler"
    targetRevision: 9.4.0
    helm:
      values: ''

