AWSTemplateFormatVersion: "2010-09-09"
Description: IAM role for serviceaccount "kube-system/autoscaler"
Resources:
  Role1:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action:
              - sts:AssumeRoleWithWebIdentity
            Condition:
              StringEquals:
                ${OIDC_URI}:aud: sts.amazonaws.com
                ${OIDC_URI}:sub: system:serviceaccount:kube-system:autoscaler
            Effect: Allow
            Principal:
              Federated: arn:aws:iam::${AWS_ACCOUNT_ID}:oidc-provider/${OIDC_URI}
        Version: "2012-10-17"
      ManagedPolicyArns:
        - arn:aws:iam::${AWS_ACCOUNT_ID}:policy/okctl-${CLUSTER_NAME}-AutoscalerServiceAccountPolicy
      PermissionsBoundary: arn:aws:iam::${AWS_ACCOUNT_ID}:policy/oslokommune/oslokommune-boundary
Outputs:
  Role1:
    Value:
      Fn::GetAtt: Role1.Arn
