apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  name: external-dns
  namespace: kube-system
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: external-dns
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: external-dns
    spec:
      containers:
      - args:
        - --source=service
        - --source=ingress
        - --domain-filter=${CLUSTER_NAME}.oslo.systems
        - --provider=aws
        - --aws-zone-type=public
        - --log-level=debug
        - --policy=upsert-only
        - --events
        - --registry=txt
        - --txt-owner-id=${HOSTED_ZONE_ID}
        image: registry.opensource.zalan.do/teapot/external-dns:v0.7.3
        imagePullPolicy: IfNotPresent
        name: external-dns
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 65534
        runAsNonRoot: false
      serviceAccount: ${SERVICEUSER_NAME}
      serviceAccountName: ${SERVICEUSER_NAME}
      terminationGracePeriodSeconds: 30
