AWSTemplateFormatVersion: 2010-09-09
Outputs:
  AutoscalerPolicy:
    Export:
      Name:
        Fn::Sub: ${AWS::StackName}-AutoscalerPolicy
    Value:
      Ref: AutoscalerPolicy
Resources:
  AutoscalerPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: Service account policy for automatically scaling the cluster nodegroup
      ManagedPolicyName: okctl-${CLUSTER_NAME}-AutoscalerServiceAccountPolicy
      PolicyDocument:
        Statement:
        - Action:
          - autoscaling:DescribeAutoScalingGroups
          - autoscaling:DescribeAutoScalingInstances
          - autoscaling:DescribeLaunchConfigurations
          - autoscaling:SetDesiredCapacity
          - autoscaling:TerminateInstanceInAutoScalingGroup
          - autoscaling:DescribeTags
          Effect: Allow
          Resource:
          - '*'
        - Action:
          - ec2:DescribeLaunchTemplateVersions
          Effect: Allow
          Resource:
          - '*'
        Version: 2012-10-17
