name: goreleaser

on:
  push:
    tags:
      - '*'

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Required. See https://goreleaser.com/ci/actions/#workflow

      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      -
        name: Get the git tag
        uses: little-core-labs/get-git-tag@v3.0.2
        id: tagName

      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: release --config ../.goreleaser.yaml --rm-dist
          workdir: ${{ steps.tagName.outputs.tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          UPGRADE_VERSION: ${{ steps.tagName.outputs.tag }}
